spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/social_media_analytics
  cache:
    cache-names: posts
    caffeine:
      spec: maximumSize=5,expireAfterAccess=3600s
server:
  port: 8080

logging:
  level:
    root: INFO
    io.github.bucket4j: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: application.log

bucket4j:
  enabled: true
  filters:
    - cache-name: posts
      url: /api/v1/posts.*
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getHeader('X-api-key')"
          execute-condition: "getHeader('X-api-key').startsWith('PX001-')"
          bandwidths:
            - capacity: 10
              time: 1
              unit: hours
        - cache-key: "getHeader('X-api-key')"
          bandwidths:
            - capacity: 5
              time: 1
              unit: hours
